"""empty message

Revision ID: 4b0d9c7191c8
Revises: fa05104e07a2
Create Date: 2022-12-17 16:42:47.132176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0d9c7191c8'
down_revision = 'fa05104e07a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('male', 'female', name='usergender'), server_default='male', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
